#! /bin/bash
# Installation d'une configuration Clojure sur Ubuntu

# put libraries in correct state
sudo apt update -y
sudo apt upgrade -y
sudo apt install software-properties-common -y

# JAVA
sudo apt install openjdk-8-jdk -y

# Clojure
mkdir install
cd install

# install clojure
sudo bash -c "curl -O https://download.clojure.org/install/linux-install-1.9.0.391.sh"
sudo chmod +x linux-install-1.9.0.391.sh
sudo ./linux-install-1.9.0.391.sh

# go back home
cd ..

# install rlwarp to use 'clj' or use 'clojure'
sudo apt install rlwrap -y

# install lein on usr/local
sudo mkdir -p /usr/local/bin/
sudo bash -c "curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > /usr/local/bin/lein"
# sudo mv ~/Downloads/lein* /usr/local/bin/lein
sudo chmod a+x /usr/local/bin/lein
lein 

# NVM
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source ~/.bashrc

# manage node
nvm install node
nvm use node

# install shadow-cljs
npm install -g shadow-cljs

# install lumo
npm install -g lumo-cljs

# install boot
sudo bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"
boot

# install app
git clone https://github.com/ivanpierre/pwa-clojure.git

cd pwa-clojure

lein clean
lein deps
lein compile
lein run

# now server is on