FROM clojure

WORKDIR /clj
ADD . /clj
VOLUME /clj

# 3449 is default http and websocket port that figwheel uses to communicate
EXPOSE 3449

EXPOSE 23

# 7888 is the default nrepl port
EXPOSE 7888

# Compile and Launch client appli
RUN lein clean
RUN lein cljsbuild once dev worker
CMD lein figwheel dev

